## arena Angel spec begin
# start:
#  position: [ -5.0,4.5,1.2]
#  velocity: [0 , 0 , 0]
# end:
#  position: [ -2.5, -6.0, 3.5 ]
#  velocity: [0 , 0 , 0]
#  gates: [[ -0.90 , -1.27 , 3.48 ],
#        [ 9.09 , 6.26 , 1.08 ],
#        [ 9.27 , -3.46 , 1.17 ],
#        [ -4.0 , -6.25 , 3.40 ],
#        [ -4.48 , -5.94 , 1.05 ],
#        [ 4.45 , -0.80 , 1.09 ],
#        [ -2.65 , 6.51 , 1.30 ],
#        [ -0.90 , -1.27 , 3.48 ],
#        [ 9.09 , 6.26 , 1.08 ],
#        [ 9.27 , -3.46 , 1.17 ],
#        [ -4.0 , -6.25 , 3.40 ],
#        [ -4.48 , -5.94 , 1.05 ],
#        [ 4.45 , -0.80 , 1.09 ],
#        [ -2.65 , 6.51 , 1.30 ],
#        [ -0.90 , -1.27 , 3.48 ],
#        [ 9.09 , 6.26 , 1.08 ],
#        [ 9.27 , -3.46 , 1.17 ]]
## gates: [[ -0.90 , -1.27 , 3.48 ],
##       [ 9.09 , 6.26 , 1.08 ],
##       [ 9.27 , -3.46 , 1.17 ]]
# #added start orientation 0 which is not fulfilled!!!
# gates_orientations: [0, 0,-20,-126,-180,0,72,-160,0,-20,-126,-180,0,72,-160,0,-20,-126,-160]
# gates_pitch_orientations: [0, 0,-0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
##Angel spec end




start:
  position: [ 0  ,    0  , 0]
  velocity: [2  , 0     , 2  ]
end:
  position: [ 6 ,    0    , 0  ]
  velocity: [0    ,  0 , 0 ]
gates: []

gates_orientations: [ 0 , -90]
gates_pitch_orientations: [0 , 0]

max_yaw_pitch_ang: 20
precision_yaw_pitch_ang: 20
end_free: True
# #added start orientation 0 which is not fulfilled!!!
# gates_orientations: [-43, 0,-20,-126]   
# # # gates_pitch_orientations: [-20,20,0,0]
# gates_pitch_orientations: [0,0,0,0]

# 8.34      6.34      0.757     12.4      4.53      -2.59    
# 9.09      6.26      1.08      10.3      -3.76     0        
# 9.27      -3.46     1.17      -6.47     -8.9      0        
# -4.75     -6.12     2.81      -11       -1.35e-15 0 

# yaw 20.1 -20 -126 -180 
# pitch 11.1 -0 -0 -0 
# norm 13.4 11 11 11 
# euler angles
# yaw
#gates_orientations: [ 0 , 0, 0 , 0 ]
#gates_pitch_orientations: [0 , 45 ,0 ,0 ]


# output tr size 3
#  yaw -40.4495 pitch -27.2011
# yaw 69.6394 pitch 22.521
# yaw 0 pitch -40
# yaw -90.5 pitch 0.866014

