# arena Angel spec begin
# start:
#  position: [ -5.0,4.5,1.2]
#  velocity: [0 , 0 , 0]
# end:
#  position: [ -2.5, -6.0, 3.5 ]
#  velocity: [0 , 0 , 0]
# # gates: [[ -0.90 , -1.27 , 3.48 ],
# #       [ 9.09 , 6.26 , 1.08 ],
# #       [ 9.27 , -3.46 , 1.17 ],
# #       [ -4.0 , -6.25 , 3.40 ],
# #       [ -4.48 , -5.94 , 1.05 ],
# #       [ 4.45 , -0.80 , 1.09 ],
# #       [ -2.65 , 6.51 , 1.30 ],
# #       [ -0.90 , -1.27 , 3.48 ],
# #       [ 9.09 , 6.26 , 1.08 ],
# #       [ 9.27 , -3.46 , 1.17 ],
# #       [ -4.0 , -6.25 , 3.40 ],
# #       [ -4.48 , -5.94 , 1.05 ],
# #       [ 4.45 , -0.80 , 1.09 ],
# #       [ -2.65 , 6.51 , 1.30 ],
# #       [ -0.90 , -1.27 , 3.48 ],
# #       [ 9.09 , 6.26 , 1.08 ],
# #       [ 9.27 , -3.46 , 1.17 ]]
# gates: [[ -0.90 , -1.27 , 3.48 ],
#       [ 9.09 , 6.26 , 1.08 ],
#       [ 9.27 , -3.46 , 1.17 ]]
# #added start orientation 0 which is not fulfilled!!!
# gates_orientations: [0, 0,-20,-126,-180,0,72,-160,0,-20,-126,-180,0,72,-160,0,-20,-126,-160]    
#Angel spec end




start:
  position: [ -3.5 ,    0.00889 , 2]
  velocity: [8.41 , -7.17 , 5.68 ]
end:
  position: [ 9.27  ,   -3.46  ,  1.17 ]
  velocity: [0 , 0 , 0]
gates: [[ -0.9,     -1.27  ,  3.48],
      [ 9.09   ,  6.26   ,  1.08  ]]

# #added start orientation 0 which is not fulfilled!!!
# gates_orientations: [-43, 0,-20,-126]   
# # # gates_pitch_orientations: [-20,20,0,0]
# gates_pitch_orientations: [0,0,0,0]

gates_orientations: [ -40.4495, 69.6394 ,0,-90.5]   
gates_pitch_orientations: [-27.2011, 22.521, 0.866014]
# output tr size 3
#  yaw -40.4495 pitch -27.2011
# yaw 69.6394 pitch 22.521
# yaw 0 pitch -40
# yaw -90.5 pitch 0.866014

max_yaw_pitch_ang: 10
precision_yaw_pitch_ang: 10

end_free: True