start:
  position: [0, 0, 0]
  velocity: [12, 0, 0]
end:
  position: [0, 14, 0]
  velocity: [-20, -20 ,0]
locations: [[10, 10, 0],
            [20, 13, 0]]

number_of_yaw_samples: 8
number_of_velocity_samples: 8
max_velocity_norm: 20



