start:
  position: [0, 0, 0]
  velocity: [50, 0, 0]
end:
  position: [40, 40, 0]
  velocity: [0, -0 ,0]
locations: [[30, 15, 0],
            [50, 45, 0],
            [70, 20, 0],
            [30, 40, 0],
            [25, 25, 0]]


rewards: [71, 71, 100, 50, 11]
number_of_angle_samples: 23
number_of_velocity_samples: 8
max_velocity_norm: 40
t_max: 4



